### ISSUE TITLE
Timing does not support times <1ms

### ISSUE THREAD

**Issue by dvirsky** [cactus/go-statsd-client#10]
The Statter API has:
`Timing(stat string, delta int64, rate float32) error`

And it expects delta to be in milliseconds. However, the protocol supports floating point numbers, and in a Python library I'm using sub-ms timings and it works perfectly fine with Graphite.

I'm dealing with sub millisecond timings in Go now, and I can't get accurate reading because of this.

Ideally, the Statter's API should look like this IMO:
`Timing(stat string, delta time.Duration, rate float32) error` 
And internally should convert to float for low numbers, and to int for larger ones. 

However, in order not to break the API, I'd add a separate method for it, e.g:
`TimingDuration(stat string, delta time.Duration, rate float32) error` 

Anyway, if you're interested I'd be happy to implement and add a PR. let me know.
Thanks :)

**Comment by cactus** [comment]
I like the TimingDuration proposal. Sounds like a great addition.
If you have time a pull request would be super.

**Comment by dvirsky** [comment]
Enjoy #11 :)

**Comment by cactus** [comment]
fixed by #11
