### ISSUE TITLE
Optimization suggestion: Avoid formatting if we're not going to send a packet

### ISSUE THREAD

**Issue by dvirsky** [cactus/go-statsd-client#12]
Right now the message formatting occurs before we decide whether the sample rate will allow the current message to be sent.

i.e.
```go
func (s *Client) Inc(stat string, value int64, rate float32) error {
	dap := fmt.Sprintf("%d|c", value) <-- causes CPU work and probably creates garbage
	return s.Raw(stat, dap, rate) // <----- this might do nothing!
}
```
I'm assuming that calculating the random sample is faster and causes no GC [citation of benchmark needed ;) ], compared to string formatting, so applications will benefit from having the sample rate checked before formatting on stats that are sent very frequently. 

This will also allow `client.Raw` to possibly do all formatting in one go, further reducing garbage and CPU.

Again, if you're interested I'll just go ahead and implement it.

**Comment by cactus** [comment]
That sounds like a good idea  -- perhaps a non exported func that handles the sampling or something similar to this?:

```
func (s *Client) Timing(stat string, delta int64, rate float32) error {
	if !inSample(rate) {
		return nil
	}
	dap := fmt.Sprintf("%d|ms", delta)
	return s.Raw(stat, dap, rate)
}

func (s *Client) inSample(rate float32) bool {
	if rate < 1 {
		if rand.Float32() < rate {
			return true
		} else {
			return false
		}
	}
	return true
}
```

**Comment by dvirsky** [comment]
Yep, something like it. And then the formatting method can be optimized as
well into one sprintf probably. I'll try to hack something later today.

**Comment by cactus** [comment]
I added some changes in 8058158d13da66354cf4eeea4614fcf379bf14fc.
Let me know if this covers your request. Got a reasonable perf boost of out it, and some other changes.

```
benchmark                       old ns/op     new ns/op     delta
BenchmarkClientInc              15159         13657         -9.91%
BenchmarkClientIncSample        5630          4637          -17.64%
BenchmarkClientSetInt           15202         13515         -11.10%
BenchmarkClientSetIntSample     5697          4602          -19.22%
```

**Comment by dvirsky** [comment]
cool. I've added some micro-optimization suggestions to the commit. 

Also, perhaps it's possible not to copy the byte buffers in the buffered client, but instead use the pooled buffers, and let the client release them when it's done sending? that way there will be less copying/allocation. shouldn't be a big change

**Comment by cactus** [comment]
After the recent commit

        benchmark                       old ns/op     new ns/op     delta
        BenchmarkClientInc              13855         13210         -4.66%
        BenchmarkClientIncSample        4654          4546          -2.32%
        BenchmarkClientSetInt           13958         13262         -4.99%
        BenchmarkClientSetIntSample     4615          4485          -2.82%

Yeah, I had planned on looking at the buffer stuff again. Note that the current code isn't even putting the buffer back into the sync.Pool. This was actually racey with the BufferedSender, because it was mutating the slice after sending it down the channel (eg. later), and sometimes the slice would get reset too early resulting in truncated metrics, as the underlying array that the slice was references was changing.

**Comment by cactus** [comment]
Since the raciness in BufferedSender was resolved by being safer and copying, I reintroduced putBuffer. Thanks for the reminder. Another nice little perf bump.

**Comment by dvirsky** [comment]
These are deltas from the previous commit, right?

**Comment by cactus** [comment]
Yeah.

Here is the latest head from the same original commit..

```
# go get -u golang.org/x/tools/cmd/benchcmp
(master)$ git co ea76b313ca75d0a41a3fd02af88326a9ce225b60 2>&-
(ea76b31...)$ go test -bench=. -run None . > /tmp/run0.txt
(ea76b31...)$ git co master 2>&-
(master)$ go test -bench=. -run None . > /tmp/run1.txt
(master)$ benchcmp /tmp/run0.txt /tmp/run1.txt 
benchmark                       old ns/op     new ns/op     delta
BenchmarkClientInc              13688         12730         -7.00%
BenchmarkClientIncSample        4653          4382          -5.82%
BenchmarkClientSetInt           13690         13189         -3.66%
BenchmarkClientSetIntSample     4605          4345          -5.65%
```

**Comment by cactus** [comment]
closing, since this was completed. reopen if needed.

**Comment by dvirsky** [comment]
what you did was perfect, thanks a lot.
