### ISSUE TITLE
Last cmd in buffered should not end with \n

### ISSUE THREAD

**Issue by rtoma** [cactus/go-statsd-client#17]
When using the buffered method each cmd added to the buffer ends with a newline character.

This caused the etsy statsd server and log zillions msgs like:
```
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
5 Oct 15:51:11 - DEBUG: Bad line: 1 in msg ""
```

Could you strip the last newline when flushing the buffer?

**Comment by cactus** [comment]
Thanks for reporting!
Fix pushed. Can you check if that resolves the problem?

**Comment by rtoma** [comment]
Fixed, like:
![image](https://cloud.githubusercontent.com/assets/2914051/10290235/382d2ec6-6ba3-11e5-8bad-ad2857326751.png)

Thanks!

**Comment by cactus** [comment]
:D
