### ISSUE TITLE
Feature Request: Non-sampled API

### ISSUE THREAD

**Issue by falun** [cactus/go-statsd-client#27]
I'm toying around with what an impl for this might look like but wanted feedback before spending much time on it.

For the most part I'm not super worried in being able to configure the sample rate for each individual stat that I'm collecting -- there are likely to be some things on the hot path that I'll want to turn down and some low-volume-but-essential things I need 100% visibility. It would be nice if there was a way to build a `Statter` with preset sample rates so that when you call `Inc` etc you don't need to provide your own sample rate.

Expressing this as code (pretending we get method overloading):

```go
func (s *Client) Inc(stat string, value int64, rate float32) error { ... }

func (s *Client) Inc(stat string, value int64) error {
    return s.Inc(stat, value, s.sampleRate)
}

```

Is this something you would not want merged in or is it worth poking at a bit more?

**Comment by cactus** [comment]
I think I would be hesitant to add that to the library, based on my current understanding of your intent. This seems like something that would be a better fit for either application specific code, or possibly a higher level convenience wrapper.

I certainly think it is worth fleshing out further though. There are likely many other conveniences/niceties that would be a better fit in a convenience wrapper layer, built atop go-statsd-client, that may not make sense at the level of abstraction targeted here.

**Comment by falun** [comment]
After spending some time trying to shoe horn this as an expansion of the core feature set without reaching modifications I ended up at the same place. It works reasonably well as a layer on top (there is some wonkiness because it breaks the assumption that only a `SubStatter` will include sampling.

Anyway, it'd look something like https://github.com/falun/go-statsd-client/commit/379bc770813199c37fa6cbf302f951e73d45046f -- would you want that contributed back as beginning of a collection usability-enhancing wrappers?

**Comment by cactus** [comment]
I think for now it makes sense to have these types of wrappers stay external. Closing for now.
