### ISSUE TITLE
Statter should support non-int values

### ISSUE THREAD

**Issue by falun** [cactus/go-statsd-client#30]
Looking at the statsd protocol (`<metricname>:<value>|<type>`) and empirical testing suggests that value should be able to be any number. This client supports only int values -- intentional decision or just haven't had a need for floats?

**Comment by cactus** [comment]
The "spec" linked from [here][1], says:

> The protocol allows for both integer and floating point values. Most implementations store
> values internally as a IEEE 754 double precision float, but many implementations and
> graphing systems only support integer values. For compatibility all values should be
> integers in the range (-2^53^, 2^53^).
> [reference][2]

Personally, I seldom end up needing floats for statsd metrics. Most cases where I do, are covered by TimingDuration (or Raw I guess). That said, I wouldn't inherently object to adding float versions of some of the methods, but I would be a bit concerned about server/proxy support and "api bloat".

Did you have a specific use case for floats, or were you just wondering about float compat in general?

[1]: https://github.com/etsy/statsd/wiki/Protocol
[2]: https://github.com/b/statsd_spec#metric-types--formats

**Comment by falun** [comment]
Ah, thanks for the link.

No use case handy -- I'm in the process of adding stat publishing to a thing and trying to preemptively have answers to questions as if/when they come up.
