### ISSUE TITLE
Release 3.1.0?

### ISSUE THREAD

**Issue by mennopruijssers** [cactus/go-statsd-client#33]
Hey!

What's the ETA on a 3.1.0 release? There are quite some interesting commits after the latest 3.0.x release: https://github.com/cactus/go-statsd-client/compare/v3.0.3...master.

**Comment by cactus** [comment]
Ah, thanks for the nudge. I can certainly tag a release.

**Comment by cactus** [comment]
[done!](https://github.com/cactus/go-statsd-client/releases/tag/v3.1.0)

**Comment by mennopruijssers** [comment]
Thanks awesome!
