### ISSUE TITLE
Is the client thread safe?

### ISSUE THREAD

**Issue by rohanag108** [cactus/go-statsd-client#39]
Can this client be used across go routines without instantiating it in every go routine?

**Comment by cactus** [comment]
Yes, both the unbufferend client and the buffered client should be "goroutine-safe". 
The unbuffered sender is serialized by the underlying fdnet ([here](https://github.com/cactus/go-statsd-client/blob/master/statsd/sender.go#L30)). The buffered sender uses a lock and swap mechanism ([here](https://github.com/cactus/go-statsd-client/blob/master/statsd/sender_buffered.go#L40)) across the buffer, to remain safe.

Just be sure that client initialization (NewClient) has been performed the err checked, before spawning any goroutines (to avoid racing on client creation itself).

**Comment by cactus** [comment]
Closing as answered. Reopen if needed.
