### ISSUE TITLE
is there anyway to see the actual data?

### ISSUE THREAD

**Issue by dangkaka** [cactus/go-statsd-client#42]
for example. When I send using
```
client, _ := statsd.NewClient("localhost:8125", "prefix")
stat.Timing("event", 42, 1.0)
```
I wonder what is the key and value we actually send
Is there any way or document to know it?

**Comment by cactus** [comment]
The general format spec is [here](https://github.com/statsd/statsd/blob/master/docs/metric_types.md). 

As for viewing the actual data on the wire, you could use ngrep to look at the packet data.

You could also look at [some tests](https://github.com/cactus/go-statsd-client/blob/master/statsd/client_test.go#L28) and see what the output format looks like for some given examples, and extrapolate.

In general though, the prefix is prefixed to the event name. So with a prefix of `"prefix"`, an event name of `"event"`, and a value of `42`, you would send `prefix.event:42|ms` (note: remember that depending on the sampling rate, data may not always sent).

**Comment by dangkaka** [comment]
oh nice, thanks a lot 🚀 
this is the best lib in town 💪
