### ISSUE TITLE
NoopClient Replacement

### ISSUE THREAD

**Issue by teamdoug** [cactus/go-statsd-client#45]
Hi,
I noticed you recently marked the "NoopClient" as deprecated with note to use a "nil *Client" instead. We are using a NoopClient in unit tests to ignore the events, but trying to use a nil *Client in the same way as a NoopClient causes a panic because it tries to call methods on the nil pointer.
Creating a client with an empty config generates errors when actually writing because it tries sending to the empty address, which show up in our unit test logs because we log errors from the various methods.
Am I misunderstanding the recommendation, or is there another way to get similar functionality?

Thanks!
Doug

**Comment by cactus** [comment]
hmm. That sounds like it might either be a bug in go-statsd-client, or perhaps a nil interface?

If you can distill your issue out of your codebase to a small example so I can reproduce it, I would love to take a look.

**Comment by teamdoug** [comment]
Thank you for the very fast response! In generating a test case, I found my issue. We have a wrapper that took a `statsd.Statter` interface, and passing `nil` to that wrapper failed. I have now learned that you can call methods on nil pointers that point to structs but not interfaces. Adding an explicit cast i.e. `(*statsd.Client)(nil)` fixed the issue. Sorry for the confusion!
