### ISSUE TITLE
Not connected, but no error is being returned

### ISSUE THREAD

**Issue by synackSA** [cactus/go-statsd-client#47]
I've been doing some test with this package and for some reason, when I try to send stat data, no connection is created (I know this because I'm not even running a server), but no error is returned.

```go
package main

import (
	"fmt"

	statsd "github.com/cactus/go-statsd-client/statsd"
)

func main() {

	conf := statsd.ClientConfig{
		Address: "127.0.0.1:8125",
		Prefix:  "",
	}

	client, err := statsd.NewClientWithConfig(&conf)
	if err != nil {
		fmt.Printf("%+v", err)
		panic(err)
	}

	err = client.Inc("test", 1, 1.0)
	if err != nil {
		fmt.Printf("%+v", err)
		panic(err)
	}
}
```

When this is run, no error is output.

There is definately no server running: 
```
» telnet 127.0.0.1 8125
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

I'm not sure what is going on here, any help appreciated. I'm using 3.2.0 version of the package:
```
[[constraint]]
  name = "github.com/cactus/go-statsd-client"
  version = "3.2.0"
```

**Comment by cactus** [comment]
The statsd data is sent via udp, not tcp. As such, you would not see any tcp connections.
To look for data on the wire, I recommend ngrep or tcpdump.

Here is an example of ngrep being run, with the go-statsd-client's `test-client` being run in another terminal:
```
$ sudo ngrep -p -d lo0 -W byline "" port 8125
interface: lo0 (127.0.0.0/255.0.0.0)
filter: ( udp port 8125 ) and (ip || ip6)
#
U 127.0.0.1:49833 -> 127.0.0.1:8125 #1
test-client.counter:1|c
#
U 127.0.0.1:49833 -> 127.0.0.1:8125 #2
test-client.counter:1|c
#
U 127.0.0.1:49833 -> 127.0.0.1:8125 #3
test-client.counter:1|c
#
U 127.0.0.1:49833 -> 127.0.0.1:8125 #4
test-client.counter:1|c
```

**Comment by cactus** [comment]
There is an old branch with tcp support -- you can view the discussion over on this issue: https://github.com/cactus/go-statsd-client/issues/14

**Comment by synackSA** [comment]
Yeah, I have the statsd server running inside docker. I originally didn't open the udp port, which is why I wasn't getting stats. That is working now, however to me it's still worrying that I have no visibility from my code's point of view if connection if I'm connected to the statsd server. Looking at the code, it _looks like_ it's supposed to be reporting on this sort of thing, but in reality it's not. No error is every set.

Maybe that should be something that is configurable? Default to fire and forget, but if errors are desired, then we can pass that in via the config?

**Comment by synackSA** [comment]
Sorry, I misunderstood what you were originally saying.

So with UDP, we have no way of knowing if a connection to the server was made or the statsd string was sent at all?

**Comment by cactus** [comment]
On unix at least, the host-os will usually return an error if the destination definition is invalid or missing (eg. not a valid ip address), and a handful of other cases (`man sendto` for some details) . Go appears to also return a file descriptor/syscall poll error in some cases (the file descriptor code in `internal/poll` and `syscall/unix/*`)-- not sure what the exact errors that may arise here, but it should be mostly stuff _before_ handing off the packet to the kernel network code.

Once the packet hits the kernel network code, being udp.. it is indeed pretty much "on its own" with no additional error reporting back up the stack.

If you need assurances that your metrics are being recorded, and/or can't miss _any_, and/or desire no sampling rates even at very high volumes, then statsd based systems probably aren't what you are looking for.

I listed a few options [here](https://github.com/cactus/go-statsd-client/issues/14#issuecomment-121468660), though there are _many_ other solutions out there.

**Comment by synackSA** [comment]
So even if the `Address` field in `ClientConfig` contains a host name that doesn't exist, or can't connect to, no error is returned?

**Comment by cactus** [comment]
If the address is a hostname, the [code](https://github.com/cactus/go-statsd-client/blob/12b4e2b38748b80f6755d1b63314b517492c7665/statsd/sender_resolving.go#L153) tries to resolve it. If the resolution fails, that is an error. If the resolution succeeds, and is a valid address (and the go network libs don't raise), then the client creation succeeds.

**Comment by synackSA** [comment]
Yeah it seems that if the host is valid no error is returned, regardless if
anything is actually listening on the port of the address

**Comment by cactus** [comment]
Correct. If the host system thinks it will be routable then it just blasts it out, and that's it.

**Comment by cactus** [comment]
Closing issue for now. Working as designed.
