### ISSUE TITLE
question to SetInt

### ISSUE THREAD

**Issue by Arnold1** [cactus/go-statsd-client#48]
hi,

I have a question to SetInt, lets say I have a for loop and call SetInt multiple times, what value gets displayed in Grafana? my Grafana refreshes a value every 30 sec.

```
SetInt("someMetrics", 10, 1.0)
SetInt("someMetrics", 15, 1.0)
SetInt("someMetrics", 7, 1.0)
SetInt("someMetrics", 9, 1.0)
SetInt("someMetrics", 11, 1.0)
```

**Comment by cactus** [comment]
[Set](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#sets) types count the number of unique values of a "set", per flush interval. Note that statsd itself aggregates values, does the counting, and handles the flushing and flush interval.

So, assuming this all happened during a given flush interval, I would expect to see `5` (as there are 5 unique values), as a result.

**Comment by Arnold1** [comment]
@cactus thanks for reply. I think SetInt was not what I was looking for. I have a request latency (ms) for a benchmark I need to display. I should use Timing right? how can I display p99, p95, p50 in Grafana when I have a timing metric?

**Comment by cactus** [comment]
Yeah, you would presumably want to use a Timing. Depending on what you are using for you backend/aggregator ([statsd](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#timing), influxdb, graphene, etc), that component would be the one to calculate and store the historgram data. Then grafana could be used to query that histogram output and construct graphs.

**Comment by bzzoop** [comment]
closing as answered.
