### ISSUE TITLE
Floating point support for gauges?

### ISSUE THREAD

**Issue by billygout** [cactus/go-statsd-client#57]
I note that our `Gauge()` function takes an `int64` `value`, and thus cannot represent floating-point values, and I have an application which uses floating point values to represent a fraction between 0 and 1. I also note that at least one other library takes a `float64` for the gauges value (see: https://github.com/DataDog/datadog-go/blob/v5.0.2/statsd/statsd.go#L504). So, I'm curious if you would consider the addition of a new function with the following signature, or the like:
`func (s *Client) FloatGauge(stat string, value float32, rate float32, tags ...Tag) error`

If so, I might be able to PR it.

**Comment by billygout** [comment]
Oops, i just realized you have a closed issue for this already: https://github.com/cactus/go-statsd-client/issues/36

I will comment there instead.

**Comment by dropwhile** [comment]
@billygout 
I added support for this to master:HEAD. Let me know if this is fit for your needs.
I'll likely tag a release in the new year if I don't hear of any breakages/issues.

Note: I added the new Floaty methods to a new interface, so as not to break existing usages... as well as to highlight that some servers may not support this extended feature-set.

Happy Holidays!
