### ISSUE TITLE
Version Number for got-statsd-client

### ISSUE THREAD

**Issue by tparikh** [cactus/go-statsd-client#8]
Hi,

I noticed that your client does not have any version number or official release number for it. Would it be possible for you guys to tag the code with a version number or create a zip file with version number? 

Thanks,
--Tejas

**Comment by cactus** [comment]
Sure. I can tag a version.

**Comment by cactus** [comment]
tag added. https://github.com/cactus/go-statsd-client/releases/tag/v1.0.0
